### ISSUE TITLE
 subprocess.run 参数需要增加shell=True

### ISSUE THREAD

**Issue by purpletpig** [Zhangtingyuxuan/voice_activity_detection#2]
subprocess.run("ffmpeg -loglevel quiet -y -i %s -acodec pcm_s16le -ac 1 -ar 16000 %s" % (audio_raw, audio_path),shell=True)

**Comment by zlzhang1124** [comment]
subprocess.run 参数里不是已经有shell=True了吗？请具体描述你的问题

**Comment by kabrate** [comment]
> subprocess.run 参数里不是已经有shell=True了吗？请具体描述你的问题

原程序里没有这个参数。不加这个参数似乎会报错。

**Comment by zlzhang1124** [comment]
> > subprocess.run 参数里不是已经有shell=True了吗？请具体描述你的问题
> 
> 原程序里没有这个参数。不加这个参数似乎会报错。

原程序里有shell=True，请检查类OpenSmileFeatureSet方法feature_extraction中的subprocess.run输入参数。

**Comment by kabrate** [comment]
是audio_split.py文件里的。

**Comment by zlzhang1124** [comment]
> 是audio_split.py文件里的。

我的环境没有报错，报错的话就加上shell=True吧
