### ISSUE TITLE
切割后的音频为什么都是0秒，用人耳听听不出分割出很好的效果

### ISSUE THREAD

**Issue by wschenpeng** [Zhangtingyuxuan/voice_activity_detection#5]
切割后的音频（detected_split2文件夹里的音频）为什么都是0秒，用人耳听听不出分割出很好的效果，我播放切割后的音频听不到清晰的数字，怎么解决？

**Comment by zlzhang1124** [comment]
> 切割后的音频（detected_split2文件夹里的音频）为什么都是0秒，用人耳听听不出分割出很好的效果，我播放切割后的音频听不到清晰的数字，怎么解决？

请确认：待分割音频是否是自己的？还是程序中原始例子？
若为原始例子，应该是能够成功分割，否则请报告；若为自己的个性化音频，请检查：1. 待分割音频是否过短？  2. 待分割音频间隔是否过短？
若无上述问题，请根据每次分割得到的分割图以及各种可视化曲线，调整分割函数中的各项参数，具体调整方法，程序中都有注释，调整时也可仅使用一次分割，即仅使用detected_split1

**Comment by wschenpeng** [comment]
> > 切割后的音频（detected_split2文件夹里的音频）为什么都是0秒，用人耳听听不出分割出很好的效果，我播放切割后的音频听不到清晰的数字，怎么解决？
> 
> 请确认：待分割音频是否是自己的？还是程序中原始例子？
> 若为原始例子，应该是能够成功分割，否则请报告；若为自己的个性化音频，请检查：1. 待分割音频是否过短？ 2. 待分割音频间隔是否过短？
> 若无上述问题，请根据每次分割得到的分割图以及各种可视化曲线，调整分割函数中的各项参数，具体调整方法，程序中都有注释，调整时也可仅使用一次分割，即仅使用detected_split1

您好，我使用的是原始的例子，蓝天白云和数字，切割后我每个音频都去听了，感觉并不是很完整，听不出来切割后的数字。

**Comment by zlzhang1124** [comment]
> > > 切割后的音频（detected_split2文件夹里的音频）为什么都是0秒，用人耳听听不出分割出很好的效果，我播放切割后的音频听不到清晰的数字，怎么解决？
> > 
> > 
> > 请确认：待分割音频是否是自己的？还是程序中原始例子？
> > 若为原始例子，应该是能够成功分割，否则请报告；若为自己的个性化音频，请检查：1. 待分割音频是否过短？ 2. 待分割音频间隔是否过短？
> > 若无上述问题，请根据每次分割得到的分割图以及各种可视化曲线，调整分割函数中的各项参数，具体调整方法，程序中都有注释，调整时也可仅使用一次分割，即仅使用detected_split1
> 
> 您好，我使用的是原始的例子，蓝天白云和数字，切割后我每个音频都去听了，感觉并不是很完整，听不出来切割后的数字。

原始数字例子（共说出了7个数字），默认参数分割，detected_split1会分割出7段，对应每一个说出的数字音频，其中由于第6个数字音频‘’88”中间有部分有一点停顿，detected_split2会把该段继续分割成两段，这里都可以用参数调整。两者得到的所有音频段都是零点几秒（通过文件属性来看当然会显示为0秒），每个听下都是正常的。不知道你所说的“感觉并不是很完整，听不出来切割后的数字”和“用人耳听听不出分割出很好的效果，我播放切割后的音频听不到清晰的数字”具体指的是什么，如果是感觉分割效果还未达到你的要求，请手动修改分割默认参数（但从该例子的分割结果来看，是已经完全分割出来的），分割效果可以通过程序执行过程中的语音波形分割图来判断。
