### ISSUE TITLE
报错怎么办

### ISSUE THREAD

**Issue by wzyloveywh** [Zhangtingyuxuan/voice_activity_detection#6]
一些数字.wav音频数据处理中...
Traceback (most recent call last):
  File "D:\vad\voice_activity_detection-master\audio_split.py", line 153, in <module>
    audio_split(input_file_folder=audio_path_raw, output_file_folder=audio_path_wav,
  File "D:\vad\voice_activity_detection-master\audio_split.py", line 76, in audio_split
    subprocess.run("ffmpeg -loglevel quiet -y -i %s -acodec pcm_s16le -ac 1 -ar 16000 %s" % (audio_raw, audio_path))
  File "D:\python3.8\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\python3.8\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\python3.8\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by zlzhang1124** [comment]
请确保电脑已安装ffmpeg，并正确设置环境变量，具体安装流程请参考网络。

**Comment by yangxiaoyang9317** [comment]
您好楼主，您的问题得到解决了吗我也出现了类似的情况我的bug如下
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg -loglevel quiet -y -i ./raw_audio/一些数字.wav -acodec pcm_s16le -ac 1 -ar 16000 ./convert2wav/一些数字.wav'
想知道您的问题最后如何解决

**Comment by zlzhang1124** [comment]
> 您好楼主，您的问题得到解决了吗我也出现了类似的情况我的bug如下 FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg -loglevel quiet -y -i ./raw_audio/一些数字.wav -acodec pcm_s16le -ac 1 -ar 16000 ./convert2wav/一些数字.wav' 想知道您的问题最后如何解决

电脑已安装ffmpeg了没，并是否正确设置环境变量呢？如果都配置正确，请确保ffmpeg拥有管理员权限（包括所运行的整个程序文件夹也要用管理员权限）
