### ISSUE TITLE
audio_split 报错

### ISSUE THREAD

**Issue by yangxiaoyang9317** [Zhangtingyuxuan/voice_activity_detection#7]
您好大神，我是看到您的这个帖子进行学习的，我在运行您的audiosplit 代码的时候出现了报错，报错如下
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg -loglevel quiet -y -i ./raw_audio/一些数字.wav -acodec pcm_s16le -ac 1 -ar 16000 ./convert2wav/一些数字.wav'

我这边环境配置也没有问题，所以想问问大神这是什么情况，谢谢大神了

**Comment by zlzhang1124** [comment]
电脑已安装ffmpeg了没，并是否正确设置环境变量呢？如果都配置正确，请确保ffmpeg拥有管理员权限（包括所运行的整个程序文件夹也要用管理员权限）

**Comment by yangxiaoyang9317** [comment]
非常感谢大神的回复，我现在去尝试一下，谢谢
